{{- $fullName := include "todo.fullname" . -}}
{{- $redisFullName := include "todo.redis.fullname" . -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-create
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: create
            env:
            - name: REDIS_HOST
            {{- if .Values.redis.enabled }}
              value: {{ template "todo.redis.host.readwrite" . }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $redisFullName }}-secret
                  key: host
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.enabled }}
                  name: {{ $redisFullName }}
                  key: redis-password
                {{- else }}
                  name: {{ $redisFullName }}-secret
                  key: password
                {{- end }}
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-create.js" | indent 4 }}
  function-content-type: text
  handler: todos.create
  runtime: nodejs8
  service:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-create
    type: ClusterIP
---
{{- $fullName := include "todo.fullname" . -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-update
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: update
            env:
            - name: REDIS_HOST
            {{- if .Values.redis.enabled }}
              value: {{ template "todo.redis.host.readwrite" . }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $redisFullName }}-secret
                  key: host
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.enabled }}
                  name: {{ $redisFullName }}
                  key: redis-password
                {{- else }}
                  name: {{ $redisFullName }}-secret
                  key: password
                {{- end }}
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-update.js" | indent 4 }}
  function-content-type: text
  handler: todos.update
  runtime: nodejs8
  service:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-update
    type: ClusterIP
---
{{- $fullName := include "todo.fullname" . -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-delete
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: delete
            env:
            - name: REDIS_HOST
            {{- if .Values.redis.enabled }}
              value: {{ template "todo.redis.host.readwrite" . }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $redisFullName }}-secret
                  key: host
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.enabled }}
                  name: {{ $redisFullName }}
                  key: redis-password
                {{- else }}
                  name: {{ $redisFullName }}-secret
                  key: password
                {{- end }}
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-delete.js" | indent 4 }}
  function-content-type: text
  handler: todos.delete
  runtime: nodejs8
  service:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-delete
    type: ClusterIP
---
{{- $fullName := include "todo.fullname" . -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-read-one
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: read-one
            env:
            - name: REDIS_HOST
            {{- if .Values.redis.enabled }}
              value: {{ template "todo.redis.host.readonly" . }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $redisFullName }}-secret
                  key: host
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.enabled }}
                  name: {{ $redisFullName }}
                  key: redis-password
                {{- else }}
                  name: {{ $redisFullName }}-secret
                  key: password
                {{- end }}
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-read-one.js" | indent 4 }}
  function-content-type: text
  handler: todos.readOne
  runtime: nodejs8
  service:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-read-one
    type: ClusterIP
---
{{- $fullName := include "todo.fullname" . -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-read-all
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: read-all
            env:
            - name: REDIS_HOST
            {{- if .Values.redis.enabled }}
              value: {{ template "todo.redis.host.readonly" . }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $redisFullName }}-secret
                  key: host
            {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.redis.enabled }}
                  name: {{ $redisFullName }}
                  key: redis-password
                {{- else }}
                  name: {{ $redisFullName }}-secret
                  key: password
                {{- end }}
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-read-all.js" | indent 4 }}
  function-content-type: text
  handler: todos.readAll
  runtime: nodejs8
  service:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-read-all
    type: ClusterIP
